parameters:
    dcs_form_geo_form_field.type.class: DCS\Form\GeoFormFieldBundle\Form\Type\GeocodeType

services:
    dcs_form_geo_form_field.type:
        class: %dcs_form_geo_form_field.type.class%
        arguments: [%form_geo_form_field.configs%]
        tags:
            - { name: form.type, alias: geocode }